# Operators and apps
Tercen operators and apps perform the computation on the projection views. An operator performs a computation on one projection. An app is a mini workflow allow a user to perform a computation or visualization.

There are many existing operators but it is easy to create your own operator. Using the data step, a user creates a projection and selects an operator. A data projection is composed of a __data__, __y-axis__, __x-axis__, __rowseq__, __colseq__, __color__ and __label__. All these projection parameter are presented by data structures to the operator.

## App library

All Tercen operators and apps are on tercen github. 


## Structure of an operator
A Tercen operator is composed of three main activities:

* Get data
* Operate on data
* Return results

All the projection parameters are available as data frames:
For the data itself Tercen supplies three variables.

``.ri``  row sequence of data, represented by an integer

``.ci``  col sequence of data, represented by an integer

``.id``      id sequence of data (will be deprecated), represented by an integer



## Tercen R package
There is currently an R package in the tercen repository to help in creating operators called ``teRcen`` 


