# Workflow and Steps {#workflow-and-steps}
Researchers want to control the data processing steps involved in the analyis of large complex data. A record of what analysis is performed is key for reproducible science. Hence Tercen has a graphical workflow editor. This allows researchers to use pre-defined workflows (e.g. taken from the app library) or if the researcher wishes, can create workflows from scratch.

A workflow consists of a series of steps. Each step is explained below.

__Table step__

Allows a researcher to select a dataset. The dataset requires to be uploaded to Tercen before it is visible for selection in the Table step.

__Data step__

Allows a researcher to create a projection for visualization and computation. 

__Gather step__

Allows a researcher to gather many factors into one factor.

__Join left step__

Allows a researcher to link to external data.

__Join right step__

Allows a researcher to link to external data.

__Query Data step__

Allows a researcher to perform a project without a computation.

__External View Data step__

Allows a researcher to connect to an external web apps (i.e. shiny app).

__Wizard step__

Maps the factors in your workflow with what is in the data.

__Input step__

Used as the first step in an app workflow.

__Output step__

Used as the last step in an app workflow.

__App step__

Is a generic term for a customized step. They are usually taken from the __app library__.

__Export step__

Used to export the result of a __data step__ as a __table__
