# Operators and Apps {#operators}

Tercen operators perform the computation on the projection views. An operator performs a computation on one projection. An app is a mini workflow allow a user to perform a computation or visualization.

There are many existing operators but it is easy to create your own operator. Using the data step, a user creates a projection and selects an operator. A data projection is composed of a __data__, __y-axis__, __x-axis__, __rowseq__, __colseq__, __color__ and __label__. All these projection parameter are presented by data structures to the operator.



## App libraries {-}

The main standard Tercen library is called, __Tercen app library__, however the full list of standard library locations are: 

* Tercen app library (located on tercen github)
* Site library (located on a tercen server)
* My library (located in the project)

The differences between the different libraries is their location and their permission.

Library  | Permission level |
:-----   | :------- |
Tercen library | Public |
Site library   | Site only|
My library     | Project only |

A __site__ is a Tercen server installed on a machine at an installation  site.

A library consists of a set of:

* Operator
* Apps
* Workflows

__Tercen app library:__

All public Tercen operators and apps are on tercen github. 

The contents of the public Tercen app library are found in a json file in [github app library](https://github.com/tercen/app-library)

The public operators and apps are also found on the Tercen github area, see (https://github.com/tercen)

## Installing apps {-}

A researcher installs an app by sourcing it from any of the libraries (tercen app library, site library, my library) or from a git repository.


## Structure of an operator {-}
A Tercen operator is composed of three main activities:

* Getting the data
* Operating on the data
* Returning the results

The data is contained in each data step. Each data step contain the data in 
three main tables:

* Row table
* Column table
* Cross-tab table

Each table contains different data as a result of the definition of the cross-tab projection.

The cross-tab table contains the following important columns, as examples:

``.ri``  row index of data, represented by an integer

``.ci``  col index of data, represented by an integer


## Tercen R package {-}
There is currently an R package in the tercen repository to help in creating operators called [teRcen](https://github.com/tercen/teRcen) 

## Creating operators {-}
The ability to create a new Tercen operator requires basic programming scills and should be straight forward.

You require to:

* Install R
* Install R Studio
* Install the [teRcen R package](https://github.com/tercen/teRcen)
* Open R Studio and create an empty project and init the git
* copy four files into project (from a operator in github)
    + `operator.json`
    + `main.R`
    + `README.md`
    + `.gitignore`
* Modify appropriately each of the files 
* Create  the `workspace.R`
  + Copy `main.R` and rename to `workspace.R` and add the following lines:
```
source('~/.Rprofile')
options("tercen.workflowId"= "76a4dcffd551802fd23d42bd862e8300")
options("tercen.stepId"= "3-2")
```
* Develop and test the __operator__ within the `workspace.R` file
    + Make view in cross-tab window
    + Get data 
    + Execute operator
    + Push data
  
Once the __operator__ is finalized then proceed:

* Modify `workshop.R` and copy it to `main.R` 
* Run `packrat::init`
This can always be redone by performing the following
    + Remove the `packrat` folder in the Rstudio project folder
    + Remove the `.Rprofile` file in the project folder
* upload to github as a public repository

You can now install your __operator__  into your Tercen server via the github install menu from the __site library__ or any __project library__ 
If you want it available to the Tercen community send an email to Tercen.
Tercen administrator makes it available by modify app library on tercen github.

__Content of `.Rprofile:` file in your home directory__ 
```
options("tercen.serviceUri"="http://127.0.0.1:5400/api/v1/")
options("tercen.username"="XXXX")
options("tercen.password"="YYYY")
```
where `XXXX` and `YYYY` are the appropiate username and password of the developer.

## Creating a Step or Workflow template {-}
* Make your workflow first
* Save the workflow
* Set the property of the workflow to “step” or "workflow"
* Download the zip of the __step__ or __workflow__
* Unzip the folder
* Add `README.md` file
* Add `.gitignore` file
* Create a git repository
* Upload the files to the git repository

## App examples {-}

__Operator examples:__

An __operator__ which performs computation follows either one of the following computing pattern :

* per cell
* per row
* per col
* per row and col


