# Deployment {#deployment}

Deployment is the manner in which Tercen is delivered to the researchers. Currently is available in two major deliveries: cloud and on-site. Each type is explained below with a brief description of some of the flavors available.

The following Tercen products are:

* __tercen.com__
* __tercen enterprise__
* __tercen studio__

The __tercen.com__ requires no installation and can be found at http:\\tercen.com

The  __tercen enterprise__ is a docker installation and runs any server or desktop, it runs on Windows, Linux and Mac.

The __tercen studio__ is for developers and runs as docker installation and includes the __tercen enterprise__ and a free __RStudio Server__.

It can be found on our [github tercen studio repository](https://github.com/tercen/tercen_studio)


# Enterprise Server

The enterprise server runs on your own servers.
The recommended high-end server specs are:

`
CPU : Xeon, 8 Cores
RAM : 64 Gig
HD  : 1TB SSD
OS  : Linux
`
Smaller servers can be used (e.g. not a Xenon but i7 or i5).
By default we recommend Linux but the Enterprise also runs on Windows and Mac OS servers.

An important rule of thumb is to have at least 8Gigs of RAM per CPU.
Hence (e.g. 4 Cores requires 32 Gigs).

